language: python

python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
  - "3.6"
#  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch

cache: pip

# command to install dependencies
install:
  - 'pip install -r requirements-tests.txt'
  - 'pip install -r requirements.txt'
  - 'pip install coveralls'

script: 
  -  'python -m pytest --junitxml ./reports/results.xml --cov-config .coveragerc --cov=src .'

after_success:
  - coveralls

deploy:
  provider: pypi
  user: mlasevich
  password:
    secure: "bPdD+7AIjegb4vdEctZEvhwk2+OWhgrbDTeaS74BF3WcY0O31qmND1F8yStobrZnQdnM9cGKKh6T5wuwA5du39DfSONXO75QzHKJqO12ntvmQP8dSLMES67CrScqHIEM+DNfkp5ZdF9PUpf7sCnMxVaSZKTbF5OUJIE9dlNU6Qzp635BXvjGgHrVrDT3m9boAERUibqmixyirjrcdb7DKRk9L/SdesTOJZGJquSQirDINY9IjZxIXUCZj4B7DB+Y9siCPHjZN2dWk/2g+oUCftUgIV9p6RN+rq5a0A2ginCaW0DJvdfKT19/vll0/dNmCNi9uKpCxVanRd9wyhIQpaRmiKv6QA0VAk+Sno2hdNU6ULlECoGnmdwL+TnoLU5DPPoNCymiCfxdnAIAGo7KD91hS0Z/A9PFZ8mYZ37pMuvgs4gouJZNNE82ZH12Lj8WiLRqBAZzMdbDtID0W1RzqWb1y+DzpgbM9WyT0443s2eEDgYdHa/dgGev+VPTAVsY+0ZqTRlCqyiBNWOI4RMCYPd2sGitrFiIRy+LZuIMlBNtuSmabZwamBrNoVeP7OSZav57cZk5VF3bFFXsmD/SsrS70hIXh/HTLW242Rl7bAFUTGlYfnwaf09zCR7W/EwmRDQwJBZSfWtJpzjNOgrY6IBr5hqdr6JywrqB3ASXZEk="
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
